[fedora_main]
image=fedora_main:latest
init=false
nvidia=true
# Must be false, pull is not compatible with localhost images
pull=false
root=false
replace=true
start_now=false
init=false
init_hooks="cat /usr/local/.bashrc >> $HOME/.bashrc"
#home=/tmp/fedora_main/home

#volume="/tmp/test:/run/a /tmp/test:/run/b"

# additiona_package="git vim"
